spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cafedb?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 7490
  jpa:
    open-in-view: false
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
    thymeleaf:
      cache: false

naver:
  url:
    search:
      local: https://openapi.naver.com/v1/search/local.json
      image: https://openapi.naver.com/v1/search/image
  client:
    id: caRXYKA5jrH0GAt5BFpf
    secret: 84Ul5Z5FiQ

kakao:
  client:
    id: 893870
    key: 2571e476ade9da7a49dfa56a093fa154
    local: https://dapi.kakao.com/v2/local/search/keyword.json
#  url:
#    search:
#      local: https://dapi.kakao.com/v2/local/search/keyword.json

